### ISSUE TITLE
Add daily water-level pcodes

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#1]
In the shiny application, allow user to retrieve additional pcodes that often contain daily measurements.  These are:
30210
72019
62600
62601
62611
62612
62613
72150
72227
72229
72230
72231
72232
72292
99019

**Comment by ldecicco-USGS** [comment]
So the list of pcodes that gets generated in the Shiny app is created from the data available for the site in question  (or at least...that's the intention...there could be a bug!). Can you describe a site(s) that are missing the pcodes?

**Comment by chopkins-usgs** [comment]
Laura,

Sure thing.  I've tried it on a number of sites, one being 433641110441501.  We should try a few sites in states that aren't coastal; that's where we'd expect those pcodes. I can send others if needed.

Thanks,
Candice

________________________________

**Comment by ldecicco-USGS** [comment]
I think this is working now, if not - feel free to re-open the issue!

**Comment by chopkins-usgs** [comment]
Now working on my end as well.  Thanks.
