### ISSUE TITLE
Long load time for explore_site() for sites with no daily data

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#23]
Reported by Virginia McGuire:

When trying to load data in explroe_site() for sites with no daily data, user experienced very long load time (10 minutes). Example site used that caused the delay is 375351097295901

**Comment by ldecicco-USGS** [comment]
When I just tested that site, clicking the "Get Daily Data" for that site (that doesn't have daily data) errored out the app (making it all grey). We should have a simple check that gives the user a message that they asked for something that doesn't exist.

@PatrickEslick ...want to take a look here:
https://github.com/USGS-R/HASP/blob/master/inst/single_site/get_data.R#L34
and try to do a similar thing in the "observeEvent(input$get_data_dv" part
I think you can check rawData_data$available_data to see if there's any dv data to get before making the actual dataRetrieval call.

**Comment by chopkins-usgs** [comment]
Yes, I've received a few comments so far from users who are getting stuck when there are no daily data.
