### ISSUE TITLE
Create documentation or instructions on how to walk through loading and exploring new sites

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#26]
A user commented that it is confusing how to walk through the explore_site() application and doesn't understand when to load data and how to click through the various graphs. 

Please create documentation showing how to load data from sites and use the various data loading options to then explore the plots generated. This package may be used broadly by the general public, so it would be nice to somehow document "first X, then Y" type steps to explore a site.

**Comment by ldecicco-USGS** [comment]
I don't have time to do this in the real near term. @PatrickEslick if you want to do it, assign yourself this task. I'd recommend creating something like:
http://usgs-r.github.io/toxEval/articles/shinyApp.html
https://github.com/USGS-R/toxEval/blob/master/vignettes/shinyApp.Rmd

Ample screen shots....

I can probably get to this mid-late next week if it still needs to be done.

**Comment by chopkins-usgs** [comment]
Similarly, this morning I received another comment that someone didn't understand how to make the map on the explore_site() application work. It would be nice to create documentation for this one too.
