### ISSUE TITLE
Add slope to chloride trends

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#30]
A user suggested that we add a non-parametric slope (Mann-Kendall and Sen) to the trend plots. That way, a user can see both the magnitude and significance of trends.

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/103025529-9ddcf500-4517-11eb-85ea-58d8d248c411.png)

That's what I added. Feel free to re-open this issue if that's not what you had in mind.
