### ISSUE TITLE
Error generated when trying to flip y-axis on "groundwater" hydrograph

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#31]
In the explore_sites() package, when a user tries to set the "flip y-axis" to FALSE on the "Groundwater" (line) plot, they get an error message: DIscrete value supplied to continuous scale.

I was able to generate this error with data from the example site

**Comment by chopkins-usgs** [comment]
However, I did not see this issue with site 434307112382601; not sure why

**Comment by ldecicco-USGS** [comment]
This seems to happen when trying to use the "lev_va" column and it's suppose to be "sl_lev_va". Adding a check in the function.
