### ISSUE TITLE
Add message to Shiny App when retrieving data for a new site

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#4]
The Shiny App is now successfully allowing users to pull data for a site and switch between sites.  However, when a new site ID is pasted, it appears as if there is no data and/or stale data from the previous site. This may be an artifact of my network connection, but I don't want users to think the app isn't working when it is in fact just loading data.

**Comment by ldecicco-USGS** [comment]
This was an issue on the code.usgs.gov repo too. My initial thoughts for that one were:

"We might want to add a "Clear Data" action button? I think it's getting confused if we load up one set of data, then start getting another set. Or, if the site gets updated (with check availability? or triggered on any of the action buttons?) we should clear out data that's not from that site?"

**Comment by chopkins-usgs** [comment]
I personally like the idea of a "Clear Data" button.  This prevents confusion between sites.
