### ISSUE TITLE
Weekly and Monthly plots not generating

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#47]
For the site 313738110102901, the monthly and daily plots do not seem to be rendering (in the Shiny app). An error code appears "Error: replacement has 2 rows, data has 1"

This error does not make sense to me as a user. In R, there's another error "Total data time span is less than 20 years".  If this is the reason for the lack of plots, we need to make that more clear for users.

**Comment by ldecicco-USGS** [comment]
Works now:
![image](https://user-images.githubusercontent.com/1105215/178812134-6a09625e-be5f-41bb-ac68-7466f250566f.png)
