### ISSUE TITLE
Help define pcodes offered in qwdata plotting options

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#48]
It appears that the "Get WQ Data" shows users any pcode that has non-daily values. This allows users to plot some strange non-numeric pcodes (such as Analyzing Agency), but that's a burden we can leave on the user for now.

It would be beneficial to somehow allow the pcodes to be defined so users understand what they are asking for. One option would be to add a link somewhere in the Shiny app with a link to the pcode definitions page: https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes

Another option would be to spell them out, but this may be complicated for sites with lots of discrete data

**Comment by ldecicco-USGS** [comment]
Switching to readWQPqw fixes this
