### ISSUE TITLE
If possible, allow axes on plots to auto-scale

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#5]
Groundwater levels at some sites are very far from zero, so  it would be ideal for the y-axis on plots to autoscale so that a user can see the full range of the hydrograph with more detail.  An example site where the details of the hydrograph are masked a bit by the scaling is site 434307112382601.

**Comment by ldecicco-USGS** [comment]
I think this sounds good. Related to #3 , maybe we should by default let all the graphs autoscale - and have a button that can flip the y axis.
