### ISSUE TITLE
Median in explanation is a diamond symbol, while a triangle shows on the plot

### ISSUE THREAD

**Issue by jmusgs** [USGS-R/HASP#65]
The explanation has a diamond symbol, while a triangle shows on he plot.  

```r
library(HASP)
library(dataRetrieval)
site <- "424520070562401"
name <- (readNWISsite(site))$station_nm
dv <- dataRetrieval::readNWISdv(site,
                                "72019",
                                statCd = "00003")
monthly_frequency_plot(dv,
                       parameter_cd = "72019",
                       plot_title = name,
                       y_axis_label = y_axis_label, flip_y = T)


```
![image](https://user-images.githubusercontent.com/16672444/166833259-c88fcceb-a4a8-4c75-bf0f-ca486c0eb8bd.png)

From the above code, what do you expect the output to be?

**Comment by ldecicco-USGS** [comment]
Latest output legend matches the data I think:
![image](https://user-images.githubusercontent.com/1105215/178611798-ec003db6-68a3-4a75-9d20-fcf33072e6b5.png)
